### ISSUE TITLE
马原教材文字版PDF

### ISSUE THREAD

**Issue by shirok1** [Dseidhit/HITSZ-OpenDS#1]
如题，下载自 Z-Library，请确认教材内容完整性。

[马克思主义基本原理（2021年版） (高等教育出版社) (z-lib.org).pdf](https://github.com/Dseidhit/HITSZ-OpenDS/files/9390352/2021.z-lib.org.pdf)

**Comment by Mor-Li** [comment]
感谢你的贡献，现已添加至仓库中
